// Shared OG image renderer with design variations.
//
// Produces 1200x630 social cards matching kanadakurniawan.com branding:
//   - dark gradient background tinted by the active palette
//   - inset rounded frame with corner accents
//   - two soft ambient gradient orbs
//   - circular profile photo with gradient ring (embedded via loadAdditionalAsset)
//   - the domain always rendered as a gradient-filled pill ("special background")
//   - optional meta chip (e.g. a tag) and subtitle
//   - deterministic layout + accent-palette variation per seed (post title)
//
// Layouts (9) — photo/text positions vary so templates can be rotated:
//   - "split"    : photo right-middle, text left
//   - "mirror"   : photo left-middle, text right-aligned
//   - "centered" : photo bottom-center, text center
//   - "gradient" : photo top-right small, text bottom-left (magazine)
//   - "minimal"  : photo top-right small, big title bottom-left (sparse)
//   - "banner"   : photo top-right small, text over horizontal gradient band
//   - "stack"    : photo top-center, text centered lower third
//   - "corner"   : photo bottom-right overlapping footer, text top-left
//   - "cover"    : large photo right bleeding off-canvas, text on soft panel
//
// Palettes (6): teal/blue, amber/pink, indigo/purple, emerald/cyan,
//               rose/orange, sky/violet. Each tints the background gradient.
//
// Branding rule: the author name appears only as "by <author>" (footerLeft),
// and the domain only as "kanadakurniawan.com" — always inside a gradient pill.
//
// Used by /og.jpg (site default), /og/[name].jpg and /og/[name].webp (per post).
// Output: JPEG q80 (mozjpeg) or WebP q85 — small and sharp.
import type { ReactNode } from "react";
import satori from "satori";
import sharp from "sharp";
import { fontData, experimental_getFontFileURL } from "astro:assets";
import { getFontPathByWeight } from "@/utils/getFontPathByWeight";
// Generated by `node scripts/build-profile-data-url.mjs` — a base64 data URL of
// the circular profile image. Inlining it avoids filesystem/Vite resolution
// uncertainty during the production build.
import { PROFILE_DATA_URL } from "@/utils/profileDataUrl";

const WIDTH = 1200;
const HEIGHT = 630;

const FG = "#e8edf2";
const MUTED = "#9db0bf";

export type OgVariant =
  | "split"
  | "centered"
  | "gradient"
  | "minimal"
  | "banner"
  | "mirror"
  | "stack"
  | "corner"
  | "cover";

type Palette = { a1: string; a2: string; bg1: string; bg2: string };

const PALETTES: Palette[] = [
  { a1: "#2dd4a8", a2: "#38a9e0", bg1: "#0c1f1d", bg2: "#0e1d2b" }, // brand    teal -> blue
  { a1: "#fb923c", a2: "#f472b6", bg1: "#241710", bg2: "#240f18" }, // warm     amber -> pink
  { a1: "#818cf8", a2: "#c084fc", bg1: "#141631", bg2: "#1b1230" }, // cool     indigo -> purple
  { a1: "#34d399", a2: "#22d3ee", bg1: "#0b1f1a", bg2: "#0a1d26" }, // fresh    emerald -> cyan
  { a1: "#fb7185", a2: "#fdba74", bg1: "#241017", bg2: "#211710" }, // sunset   rose -> orange
  { a1: "#38bdf8", a2: "#a78bfa", bg1: "#0c1f2e", bg2: "#141231" }, // aurora   sky -> violet
];

type Design = { variant: OgVariant; palette: Palette };

export type OgInput = {
  /** Main heading (post title or site title). */
  title: string;
  /** Optional sub-line above the title (e.g. site description). */
  subtitle?: string;
  /** Optional small chip label (e.g. a tag or category). */
  meta?: string;
  /** Footer-left text — the single place the author name may appear ("by …"). */
  footerLeft?: string;
  /** Footer-right text — the domain; rendered as a gradient pill everywhere. */
  footerRight: string;
  /** Force a layout variant (default: derived deterministically from title). */
  variant?: OgVariant;
  /** Force an accent palette index 0..5 (default: derived from title). */
  palette?: 0 | 1 | 2 | 3 | 4 | 5;
};

type FontSpec = {
  name: string;
  data: ArrayBuffer;
  weight: number;
  style: "normal" | "italic";
};

function hashString(str: string): number {
  let h = 0;
  for (let i = 0; i < str.length; i++) {
    h = (h * 31 + str.charCodeAt(i)) >>> 0;
  }
  return h;
}

const VARIANTS: OgVariant[] = [
  "split",
  "centered",
  "gradient",
  "minimal",
  "banner",
  "mirror",
  "stack",
  "corner",
  "cover",
];

/** Deterministic design selection seeded by the post/site title. */
export function pickDesign(
  title: string,
  variant?: OgVariant,
  palette?: 0 | 1 | 2 | 3 | 4 | 5
): Design {
  const h = hashString(title);
  return {
    variant: variant ?? VARIANTS[h % VARIANTS.length],
    palette: PALETTES[palette ?? ((h >> 3) % PALETTES.length)],
  };
}

async function loadFonts(siteUrl: URL): Promise<FontSpec[]> {
  const fonts = fontData["--font-google-sans-code"];
  const regularPath = getFontPathByWeight(fonts, 400);
  const boldPath = getFontPathByWeight(fonts, 700);
  if (!regularPath || !boldPath) {
    throw new Error("Cannot find Google Sans Code font paths.");
  }

  const [regular, bold] = await Promise.all([
    fetch(experimental_getFontFileURL(regularPath, siteUrl)).then(r =>
      r.arrayBuffer()
    ),
    fetch(experimental_getFontFileURL(boldPath, siteUrl)).then(r =>
      r.arrayBuffer()
    ),
  ]);

  return [
    { name: "Google Sans Code", data: regular, weight: 400, style: "normal" },
    { name: "Google Sans Code", data: bold, weight: 700, style: "normal" },
  ];
}

function hexToRgba(hex: string, alpha: number): string {
  const h = hex.replace("#", "");
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

// Short connector words kept lowercase in Title Case (except when first).
const TITLE_CASE_MINOR = new Set([
  "a",
  "an",
  "and",
  "at",
  "by",
  "for",
  "in",
  "of",
  "on",
  "or",
  "the",
  "to",
  "with",
]);

function toTitleCase(str: string): string {
  return str
    .split(/\s+/)
    .map((word, i, arr) => {
      const trimmed = word.replace(/[.!?]$/, "");
      const punct = word.slice(trimmed.length);
      const lower = trimmed.toLowerCase();
      const isFirst = i === 0;
      const isLast = i === arr.length - 1;
      if (
        !isFirst &&
        !isLast &&
        TITLE_CASE_MINOR.has(lower) &&
        !/[A-Z]/.test(trimmed.slice(1))
      ) {
        return trimmed + punct;
      }
      return trimmed.charAt(0).toUpperCase() + trimmed.slice(1) + punct;
    })
    .join(" ");
}

function photo(diameter: number): ReactNode {
  return {
    type: "img",
    props: {
      src: PROFILE_DATA_URL,
      width: diameter,
      height: diameter,
      style: {
        borderRadius: diameter / 2,
        flexShrink: 0,
      },
    },
  };
}

/**
 * The domain, always rendered as a gradient-filled pill (special background).
 */
function domainPill(input: OgInput, d: Design, small = false): ReactNode {
  return {
    type: "div",
    props: {
      style: {
        display: "flex",
        fontSize: small ? 15 : 17,
        letterSpacing: 2,
        fontWeight: 700,
        color: "#0a1218",
        background: `linear-gradient(90deg, ${d.palette.a1}, ${d.palette.a2})`,
        borderRadius: 999,
        padding: small ? "6px 14px" : "8px 18px",
      },
      children: String(input.footerRight ?? "").toUpperCase(),
    },
  };
}

/** Optional outlined chip (e.g. tag / category). */
function metaPill(input: OgInput, d: Design, opts?: { [key: string]: string }): ReactNode | null {
  if (!input.meta) return null;
  return {
    type: "div",
    props: {
      style: {
        display: "flex",
        fontSize: 14,
        letterSpacing: 2,
        fontWeight: 700,
        color: d.palette.a2,
        border: `1px solid ${hexToRgba(d.palette.a2, 0.65)}`,
        borderRadius: 999,
        padding: "6px 14px",
        ...opts,
      },
      children: String(input.meta).toUpperCase(),
    },
  };
}

function footer(input: OgInput, d: Design, extra?: { [key: string]: string }): ReactNode {
  return {
    type: "div",
    props: {
      style: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        fontSize: 20,
        color: MUTED,
        borderTop: "1px solid rgba(255,255,255,0.12)",
        paddingTop: 20,
        ...extra,
      },
      children: [
        { type: "span", props: { children: input.footerLeft ?? "" } },
        domainPill(input, d),
      ],
    },
  };
}

/**
 * Shared elegant decoration: inset rounded frame, corner accents (dots),
 * and two soft ambient gradient orbs.
 */
function decor(d: Design): ReactNode[] {
  const pad = 20;
  const dot = (pos: { [key: string]: string | number }): ReactNode => ({
    type: "div",
    props: {
      style: {
        position: "absolute",
        width: 9,
        height: 9,
        borderRadius: 5,
        background: d.palette.a2,
        opacity: 0.75,
        ...pos,
      },
      children: "",
    },
  });

  return [
    // inset frame
    {
      type: "div",
      props: {
        style: {
          position: "absolute",
          top: pad,
          left: pad,
          right: pad,
          bottom: pad,
          borderRadius: 26,
          border: "1px solid rgba(255,255,255,0.14)",
        },
        children: "",
      },
    },
    // ambient orbs
    {
      type: "div",
      props: {
        style: {
          position: "absolute",
          top: "-140px",
          left: "-120px",
          width: 460,
          height: 460,
          borderRadius: "50%",
          background: `linear-gradient(135deg, ${d.palette.a1}, ${d.palette.a2})`,
          opacity: 0.1,
        },
        children: "",
      },
    },
    {
      type: "div",
      props: {
        style: {
          position: "absolute",
          bottom: "-160px",
          right: "-140px",
          width: 520,
          height: 520,
          borderRadius: "50%",
          background: `linear-gradient(315deg, ${d.palette.a2}, ${d.palette.a1})`,
          opacity: 0.11,
        },
        children: "",
      },
    },
    // corner accents (dots)
    dot({ top: 32, left: 32 }),
    dot({ top: 32, right: 32 }),
    dot({ bottom: 32, left: 32 }),
    dot({ bottom: 32, right: 32 }),
  ];
}

function baseRoot(children: ReactNode[], d: Design, extra?: { [key: string]: string }): ReactNode {
  return {
    type: "div",
    props: {
      style: {
        display: "flex",
        flexDirection: "column",
        position: "relative",
        width: "100%",
        height: "100%",
        background: `linear-gradient(140deg, ${d.palette.bg1}, ${d.palette.bg2})`,
        color: FG,
        fontFamily: "Google Sans Code",
        padding: "48px",
        overflow: "hidden",
        ...extra,
      },
      children: [...decor(d), ...children],
    },
  };
}

function accentBar(d: Design, width: number): ReactNode {
  return {
    type: "div",
    props: {
      style: {
        display: "flex",
        height: 5,
        width,
        background: `linear-gradient(90deg, ${d.palette.a1}, ${d.palette.a2})`,
        borderRadius: 3,
      },
      children: "",
    },
  };
}

function titleNode(input: OgInput, fontSize: number, extra?: { [key: string]: string }): ReactNode {
  return {
    type: "div",
    props: {
      style: {
        display: "flex",
        fontSize,
        fontWeight: 700,
        lineHeight: 1.1,
        overflow: "hidden",
        color: FG,
        ...extra,
      },
      children: input.title,
    },
  };
}

function subtitleNode(input: OgInput, opts?: { [key: string]: string }): ReactNode | null {
  return input.subtitle
    ? {
        type: "div",
        props: {
          style: {
            display: "flex",
            fontSize: 21,
            color: MUTED,
            overflow: "hidden",
            ...opts,
          },
          children: toTitleCase(input.subtitle),
        },
      }
    : null;
}

/* ------------------------------ layouts ------------------------------ */

function buildSplit(input: OgInput, d: Design): ReactNode {
  return baseRoot(
    [
      {
        type: "div",
        props: {
          style: {
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            flexGrow: 1,
            gap: "50px",
          },
          children: [
            {
              type: "div",
              props: {
                style: { display: "flex", flexDirection: "column", flex: 1, minWidth: 0 },
                children: [
                  metaPill(input, d),
                  subtitleNode(input, { marginTop: 20 }),
                  titleNode(input, 60, { marginTop: 4 }),
                  { type: "div", props: { style: { display: "flex", marginTop: 24 }, children: accentBar(d, 180) } },
                ],
              },
            },
            photo(280),
          ],
        },
      },
      footer(input, d),
    ],
    d
  );
}

function buildMirror(input: OgInput, d: Design): ReactNode {
  return baseRoot(
    [
      {
        type: "div",
        props: {
          style: {
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            flexGrow: 1,
            gap: "50px",
          },
          children: [
            photo(280),
            {
              type: "div",
              props: {
                style: {
                  display: "flex",
                  flexDirection: "column",
                  flex: 1,
                  minWidth: 0,
                  alignItems: "flex-end",
                  textAlign: "right",
                },
                children: [
                  metaPill(input, d),
                  titleNode(input, 60, { marginTop: 18 }),
                  subtitleNode(input, { marginTop: 12 }),
                  { type: "div", props: { style: { display: "flex", marginTop: 22 }, children: accentBar(d, 120) } },
                ],
              },
            },
          ],
        },
      },
      footer(input, d),
    ],
    d
  );
}

function buildCentered(input: OgInput, d: Design): ReactNode {
  return baseRoot(
    [
      {
        type: "div",
        props: {
          style: {
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            flexGrow: 1,
            textAlign: "center",
            maxWidth: 960,
            marginLeft: "auto",
            marginRight: "auto",
            width: "100%",
          },
          children: [
            metaPill(input, d),
            subtitleNode(input, { marginTop: 20 }),
            titleNode(input, 52, { marginTop: 4 }),
            { type: "div", props: { style: { display: "flex", marginTop: 22 }, children: accentBar(d, 110) } },
            { type: "div", props: { style: { display: "flex", marginTop: 24 }, children: photo(140) } },
          ],
        },
      },
      footer(input, d, { position: "absolute", bottom: 34, left: 48, right: 48 }),
    ],
    d,
    { padding: "48px 60px 84px", justifyContent: "center" }
  );
}

function buildGradient(input: OgInput, d: Design): ReactNode {
  return baseRoot(
    [
      {
        type: "div",
        props: {
          style: {
            display: "flex",
            flexDirection: "column",
            flexGrow: 1,
            position: "relative",
          },
          children: [
            {
              type: "div",
              props: {
                style: {
                  display: "flex",
                  flexDirection: "row",
                  alignItems: "center",
                  justifyContent: "space-between",
                  width: "100%",
                },
                children: [photo(120)],
              },
            },
            { type: "div", props: { style: { flexGrow: 1 }, children: "" } },
            metaPill(input, d),
            titleNode(input, 62, { marginTop: 10 }),
            subtitleNode(input, { marginTop: 14 }),
          ],
        },
      },
      footer(input, d),
    ],
    d
  );
}

function buildMinimal(input: OgInput, d: Design): ReactNode {
  return baseRoot(
    [
      {
        type: "div",
        props: {
          style: {
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            width: "100%",
            position: "relative",
          },
          children: [metaPill(input, d), photo(112)],
        },
      },
      { type: "div", props: { style: { flexGrow: 1 }, children: "" } },
      {
        type: "div",
        props: {
          style: { display: "flex", flexDirection: "column", position: "relative" },
          children: [
            subtitleNode(input),
            titleNode(input, 64, { marginTop: 6 }),
            { type: "div", props: { style: { display: "flex", marginTop: 22 }, children: accentBar(d, 90) } },
          ],
        },
      },
      footer(input, d, { paddingTop: 18 }),
    ],
    d
  );
}

function buildBanner(input: OgInput, d: Design): ReactNode {
  return baseRoot(
    [
      {
        type: "div",
        props: {
          style: {
            position: "absolute",
            left: 0,
            right: 0,
            top: "34%",
            height: 190,
            background: `linear-gradient(90deg, ${hexToRgba(d.palette.a1, 0.45)}, ${hexToRgba(d.palette.a2, 0.45)})`,
            transform: "rotate(-2deg)",
          },
          children: "",
        },
      },
      {
        type: "div",
        props: {
          style: {
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            width: "100%",
            position: "relative",
          },
          children: [photo(112)],
        },
      },
      { type: "div", props: { style: { flexGrow: 1 }, children: "" } },
      {
        type: "div",
        props: {
          style: {
            display: "flex",
            flexDirection: "column",
            position: "relative",
            marginLeft: "8px",
          },
          children: [
            metaPill(input, d),
            titleNode(input, 56, { marginTop: 8 }),
            subtitleNode(input, { marginTop: 12 }),
          ],
        },
      },
      footer(input, d),
    ],
    d
  );
}

function buildStack(input: OgInput, d: Design): ReactNode {
  return baseRoot(
    [
      {
        type: "div",
        props: {
          style: {
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            flexGrow: 1,
            justifyContent: "center",
            textAlign: "center",
          },
          children: [
            photo(150),
            metaPill(input, d, { marginTop: 18 }),
            titleNode(input, 52, { marginTop: 18, textAlign: "center" }),
            subtitleNode(input, { marginTop: 12, textAlign: "center" }),
            { type: "div", props: { style: { display: "flex", marginTop: 22 }, children: accentBar(d, 100) } },
          ],
        },
      },
      footer(input, d),
    ],
    d
  );
}

function buildCorner(input: OgInput, d: Design): ReactNode {
  return baseRoot(
    [
      {
        type: "div",
        props: {
          style: { display: "flex", flexDirection: "column", flex: 1, minWidth: 0 },
          children: [
            metaPill(input, d),
            subtitleNode(input, { marginTop: 18 }),
            titleNode(input, 58, { marginTop: 4 }),
            { type: "div", props: { style: { display: "flex", marginTop: 22 }, children: accentBar(d, 140) } },
          ],
        },
      },
      { type: "div", props: { style: { flexGrow: 1 }, children: "" } },
      {
        type: "div",
        props: {
          style: {
            display: "flex",
            flexDirection: "row",
            justifyContent: "flex-end",
            alignItems: "flex-end",
            width: "100%",
            marginTop: 18,
          },
          children: photo(240),
        },
      },
      footer(input, d),
    ],
    d
  );
}

function buildCover(input: OgInput, d: Design): ReactNode {
  return baseRoot(
    [
      {
        type: "div",
        props: {
          style: {
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            flexGrow: 1,
            gap: "48px",
          },
          children: [
            {
              type: "div",
              props: {
                style: {
                  display: "flex",
                  flexDirection: "column",
                  flex: 1,
                  minWidth: 0,
                  background: "rgba(255,255,255,0.05)",
                  border: "1px solid rgba(255,255,255,0.14)",
                  borderRadius: 26,
                  padding: "38px 42px",
                },
                children: [
                  metaPill(input, d, { marginTop: 16 }),
                  subtitleNode(input, { marginTop: 20 }),
                  titleNode(input, 54, { marginTop: 4 }),
                  { type: "div", props: { style: { display: "flex", marginTop: 22 }, children: accentBar(d, 160) } },
                ],
              },
            },
            photo(300),
          ],
        },
      },
      footer(input, d),
    ],
    d
  );
}

function buildTree(input: OgInput, d: Design): ReactNode {
  switch (d.variant) {
    case "mirror":
      return buildMirror(input, d);
    case "centered":
      return buildCentered(input, d);
    case "gradient":
      return buildGradient(input, d);
    case "minimal":
      return buildMinimal(input, d);
    case "banner":
      return buildBanner(input, d);
    case "stack":
      return buildStack(input, d);
    case "corner":
      return buildCorner(input, d);
    case "cover":
      return buildCover(input, d);
    default:
      return buildSplit(input, d);
  }
}

type Format = "jpeg" | "webp";

async function render(
  input: OgInput,
  siteUrl: URL,
  format: Format
): Promise<{ buffer: Buffer; contentType: string }> {
  const fonts = await loadFonts(siteUrl);
  const design = pickDesign(input.title, input.variant, input.palette);

  const svg = await satori(buildTree(input, design), {
    width: WIDTH,
    height: HEIGHT,
    embedFont: true,
    fonts,
    // Resolve the embedded profile image to its inline data URL.
    loadAdditionalAsset: () => PROFILE_DATA_URL,
  });

  const svgBuffer = Buffer.from(
    typeof svg === "string" ? svg : Buffer.from(svg as Uint8Array),
    "utf-8"
  );

  let buffer: Buffer;
  let contentType: string;
  if (format === "webp") {
    buffer = await sharp(svgBuffer).webp({ quality: 85, effort: 6 }).toBuffer();
    contentType = "image/webp";
  } else {
    buffer = await sharp(svgBuffer)
      .jpeg({ quality: 80, mozjpeg: true, progressive: true })
      .toBuffer();
    contentType = "image/jpeg";
  }

  return { buffer, contentType };
}

export function renderOgJpeg(input: OgInput, siteUrl: URL) {
  return render(input, siteUrl, "jpeg");
}

export function renderOgWebp(input: OgInput, siteUrl: URL) {
  return render(input, siteUrl, "webp");
}